# Generated by Django 5.0.6 on 2024-06-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0002_brand_active'),
        ('customer', '0002_customer_active'),
        ('model', '0002_model_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=100)),
                ('hours_sailed', models.PositiveIntegerField()),
                ('year_of_manufacture', models.IntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='vessel_photos/')),
                ('registration_type', models.CharField(choices=[('BAR_ALU', 'Barco de Alumínio'), ('ESC', 'Escuna'), ('JET_BOAT', 'Jet Boat'), ('LAN', 'Lancha'), ('MOT_AQU', 'Moto Aquática'), ('VEL', 'Veleiro'), ('IAT', 'Iate'), ('CAN', 'Canoa'), ('CAI', 'Caiaque'), ('BAL', 'Balsa'), ('BAR_PES', 'Barco de Pesca'), ('CAT', 'Catamarã'), ('SUB', 'Submarino'), ('CARG', 'Navio de Carga'), ('PAS', 'Navio de Passageiros'), ('TAN', 'Navio Tanque'), ('DRA', 'Draga'), ('REB', 'Rebocador'), ('FRA', 'Fragata'), ('POR_AVI', 'Porta-aviões')], max_length=8)),
                ('general_observations', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='brand.brand')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='customer.customer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='model.model')),
            ],
        ),
    ]
