# Generated by Django 5.0.6 on 2024-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
